# Generated by Django 4.2.6 on 2023-10-08 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_transaction_user_delete_appuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emi',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('emi_amount', models.FloatField()),
                ('emi_principle', models.FloatField()),
                ('emi_intrest', models.FloatField()),
                ('deu_date', models.DateField()),
                ('is_payment_made', models.BooleanField(blank=True, default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('loan_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('loan_type', models.CharField(choices=[('Car', 'car'), ('Home', 'home'), ('Educational', 'educational'), ('Personal', 'personal')], max_length=30)),
                ('ammount', models.FloatField()),
                ('intrest', models.FloatField(blank=True, default=0)),
                ('term_period', models.IntegerField()),
                ('intrest_rate', models.FloatField()),
                ('disbursement_date', models.DateField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('paid_ammount', models.FloatField(blank=True, default=0)),
                ('payment_date', models.DateField(blank=True)),
                ('emi_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userloan.emi')),
                ('loan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userloan.loan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='emi',
            name='loan_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userloan.loan'),
        ),
        migrations.AddField(
            model_name='emi',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
