# Generated by Django 4.2.6 on 2023-10-08 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userloan', '0002_alter_loan_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='emi_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userloan.emi'),
        ),
    ]
