# Generated by Django 4.2.6 on 2023-10-08 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_transaction_user_delete_appuser'),
        ('userloan', '0003_alter_payment_emi_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emi',
            name='loan_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emi_loan_rel', to='userloan.loan'),
        ),
        migrations.AlterField(
            model_name='emi',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emi_user_rel', to='users.user'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_user_rel', to='users.user'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='emi_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pmnt_emi_rel', to='userloan.emi'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='loan_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pmnt_loan_rel', to='userloan.loan'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pmnt_user_rel', to='users.user'),
        ),
    ]
